# Copyright (C) 2015 The Dokdo Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j1mini3g/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/j1mini3g/proprietary/bin/at_distributor:system/bin/at_distributor \
    vendor/samsung/j1mini3g/proprietary/bin/bih_config.sh:system/bin/bih_config.sh \
    vendor/samsung/j1mini3g/proprietary/bin/calibration_init:system/bin/calibration_init \
    vendor/samsung/j1mini3g/proprietary/bin/connfwexe:system/bin/connfwexe \
    vendor/samsung/j1mini3g/proprietary/bin/ddexe:system/bin/ddexe \
    vendor/samsung/j1mini3g/proprietary/bin/engpc:system/bin/engpc \
    vendor/samsung/j1mini3g/proprietary/bin/ext_data.sh:system/bin/ext_data.sh \
    vendor/samsung/j1mini3g/proprietary/bin/ext_kill.sh:system/bin/ext_kill.sh \
    vendor/samsung/j1mini3g/proprietary/bin/ext_symlink.sh:system/bin/ext_symlink.sh \
    vendor/samsung/j1mini3g/proprietary/bin/inputfreq.sh:system/bin/inputfreq.sh \
    vendor/samsung/j1mini3g/proprietary/bin/macloader:system/bin/macloader \
    vendor/samsung/j1mini3g/proprietary/bin/mfgloader:system/bin/mfgloader \
    vendor/samsung/j1mini3g/proprietary/bin/modem_control:system/bin/modem_control \
    vendor/samsung/j1mini3g/proprietary/bin/modemd:system/bin/modemd \
    vendor/samsung/j1mini3g/proprietary/bin/nvitemd:system/bin/nvitemd \
    vendor/samsung/j1mini3g/proprietary/bin/phoneserver:system/bin/phoneserver \
    vendor/samsung/j1mini3g/proprietary/bin/prepare_param.sh:system/bin/prepare_param.sh \
    vendor/samsung/j1mini3g/proprietary/bin/recoveryfreq.sh:system/bin/recoveryfreq.sh \
    vendor/samsung/j1mini3g/proprietary/bin/refnotify:system/bin/refnotify \
    vendor/samsung/j1mini3g/proprietary/bin/rild:system/bin/rild \
    vendor/samsung/j1mini3g/proprietary/bin/rild_sprd:system/bin/rild_sprd \
    vendor/samsung/j1mini3g/proprietary/bin/scs:system/bin/scs \
    vendor/samsung/j1mini3g/proprietary/bin/smdexe:system/bin/smdexe \
    vendor/samsung/j1mini3g/proprietary/bin/wlandutservice:system/bin/wlandutservice \
    vendor/samsung/j1mini3g/proprietary/etc/connectivity_calibration.ini:system/etc/connectivity_calibration.ini \
    vendor/samsung/j1mini3g/proprietary/etc/connectivity_configure.ini:system/etc/connectivity_configure.ini \
    vendor/samsung/j1mini3g/proprietary/etc/feature_default.xml:system/etc/feature_default.xml \
    vendor/samsung/j1mini3g/proprietary/etc/firmware/sc2331_fdl.bin:system/etc/firmware/sc2331_fdl.bin \
    vendor/samsung/j1mini3g/proprietary/etc/firmware/sc2331_fw.bin:system/etc/firmware/sc2331_fw.bin \
    vendor/samsung/j1mini3g/proprietary/etc/floating_feature.xml:system/etc/floating_feature.xml \
    vendor/samsung/j1mini3g/proprietary/etc/gps.conf:system/etc/gps.conf \
    vendor/samsung/j1mini3g/proprietary/etc/gps.xml:system/etc/gps.xml \
    vendor/samsung/j1mini3g/proprietary/etc/nwk_info.xml:system/etc/nwk_info.xml \
    vendor/samsung/j1mini3g/proprietary/etc/purenandpackages_pref.txt:system/etc/purenandpackages_pref.txt \
    vendor/samsung/j1mini3g/proprietary/etc/purenandpackages.txt:system/etc/purenandpackages.txt \
    vendor/samsung/j1mini3g/proprietary/etc/spn-conf.xml:system/etc/spn-conf.xml \
    vendor/samsung/j1mini3g/proprietary/lib/hw/camera.sc8830.so:system/lib/hw/camera.sc8830.so \
    vendor/samsung/j1mini3g/proprietary/lib/hw/gps.default.so:system/lib/hw/gps.default.so \
    vendor/samsung/j1mini3g/proprietary/lib/hw/sensors.sc8830.so:system/lib/hw/sensors.sc8830.so \
    vendor/samsung/j1mini3g/proprietary/lib/libaccauthentication_jni.so:system/lib/libaccauthentication_jni.so \
    vendor/samsung/j1mini3g/proprietary/lib/libae.so:system/lib/libae.so \
    vendor/samsung/j1mini3g/proprietary/lib/libaf_running.so:system/lib/libaf_running.so \
    vendor/samsung/j1mini3g/proprietary/lib/libAF.so:system/lib/libAF.so \
    vendor/samsung/j1mini3g/proprietary/lib/libaf_tune.so:system/lib/libaf_tune.so \
    vendor/samsung/j1mini3g/proprietary/lib/libAl_Awb_v1.so:system/lib/libAl_Awb_v1.so \
    vendor/samsung/j1mini3g/proprietary/lib/libatchannel.so:system/lib/libatchannel.so \
    vendor/samsung/j1mini3g/proprietary/lib/libatparser.so:system/lib/libatparser.so \
    vendor/samsung/j1mini3g/proprietary/lib/libawb.so:system/lib/libawb.so \
    vendor/samsung/j1mini3g/proprietary/lib/libboost.so:system/lib/libboost.so \
    vendor/samsung/j1mini3g/proprietary/lib/libbt-aptx-4.0.3.so:system/lib/libbt-aptx-4.0.3.so \
    vendor/samsung/j1mini3g/proprietary/lib/libbt-codec_aptx.so:system/lib/libbt-codec_aptx.so \
    vendor/samsung/j1mini3g/proprietary/lib/libbt-codec_sshd.so:system/lib/libbt-codec_sshd.so \
    vendor/samsung/j1mini3g/proprietary/lib/libbt-iopdb_mod.so:system/lib/libbt-iopdb_mod.so \
    vendor/samsung/j1mini3g/proprietary/lib/libbt-iopdb.so:system/lib/libbt-iopdb.so \
    vendor/samsung/j1mini3g/proprietary/lib/libcalibration.so:system/lib/libcalibration.so \
    vendor/samsung/j1mini3g/proprietary/lib/libcm.so:system/lib/libcm.so \
    vendor/samsung/j1mini3g/proprietary/lib/libdeflicker.so:system/lib/libdeflicker.so \
    vendor/samsung/j1mini3g/proprietary/lib/lib_DNSe_EP_ver216c.so:system/lib/lib_DNSe_EP_ver216c.so \
    vendor/samsung/j1mini3g/proprietary/lib/libengmode.so:system/lib/libengmode.so \
    vendor/samsung/j1mini3g/proprietary/lib/libfactoryutil.so:system/lib/libfactoryutil.so \
    vendor/samsung/j1mini3g/proprietary/lib/liblcsagent.so:system/lib/liblcsagent.so \
    vendor/samsung/j1mini3g/proprietary/lib/liblsc.so:system/lib/liblsc.so \
    vendor/samsung/j1mini3g/proprietary/lib/libmemoryheapion.so:system/lib/libmemoryheapion.so \
    vendor/samsung/j1mini3g/proprietary/lib/libomission_avoidance.so:system/lib/libomission_avoidance.so \
    vendor/samsung/j1mini3g/proprietary/lib/libreference-ril.so:system/lib/libreference-ril.so \
    vendor/samsung/j1mini3g/proprietary/lib/libreference-ril_sp.so:system/lib/libreference-ril_sp.so \
    vendor/samsung/j1mini3g/proprietary/lib/libril.so:system/lib/libril.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsaiv_codec.so:system/lib/libsaiv_codec.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsAMRNB.so:system/lib/libsAMRNB.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsAMRWB.so:system/lib/libsAMRWB.so \
    vendor/samsung/j1mini3g/proprietary/lib/lib_Samsung_AudioZoom_v102.so:system/lib/lib_Samsung_AudioZoom_v102.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsamsungearcare.so:system/lib/libsamsungearcare.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsamsungeffect.so:system/lib/libsamsungeffect.so \
    vendor/samsung/j1mini3g/proprietary/lib/libSamsungMusic_v4.so:system/lib/libSamsungMusic_v4.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsamsungpowersound.so:system/lib/libsamsungpowersound.so \
    vendor/samsung/j1mini3g/proprietary/lib/libSamsungPreProcess.so:system/lib/libSamsungPreProcess.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsamsungRecord.so:system/lib/libsamsungRecord.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsamsungRecord_zoom.so:system/lib/libsamsungRecord_zoom.so \
    vendor/samsung/j1mini3g/proprietary/lib/lib_SamsungRec_V04013.so:system/lib/lib_SamsungRec_V04013.so \
    vendor/samsung/j1mini3g/proprietary/lib/lib_Samsung_Resampler.so:system/lib/lib_Samsung_Resampler.so \
    vendor/samsung/j1mini3g/proprietary/lib/lib_Samsung_SB_AM_for_ICS_v03008.so:system/lib/lib_Samsung_SB_AM_for_ICS_v03008.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsamsungSoundbooster.so:system/lib/libsamsungSoundbooster.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsdp_crypto.so:system/lib/libsdp_crypto.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsec_devenc.so:system/lib/libsec_devenc.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsecnativefeature.so:system/lib/libsecnativefeature.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsecril-client.so:system/lib/libsecril-client.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsetproperty.so:system/lib/libsetproperty.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsfextaac.so:system/lib/libsfextaac.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsfextavi.so:system/lib/libsfextavi.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsfextcmn.so:system/lib/libsfextcmn.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsfextcp.so:system/lib/libsfextcp.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsfextflac.so:system/lib/libsfextflac.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsfextflv.so:system/lib/libsfextflv.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsfextmkv.so:system/lib/libsfextmkv.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsfextmp4f.so:system/lib/libsfextmp4f.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsfextrmf.so:system/lib/libsfextrmf.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsfextwmf.so:system/lib/libsfextwmf.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsft_af_ctrl.so:system/lib/libsft_af_ctrl.so \
    vendor/samsung/j1mini3g/proprietary/lib/libshdace.so:system/lib/libshdace.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsimageis_jni.so:system/lib/libsimageis_jni.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsomp.so:system/lib/libsomp.so \
    vendor/samsung/j1mini3g/proprietary/lib/lib_SoundAlive_3DPosition_ver107.so:system/lib/lib_SoundAlive_3DPosition_ver107.so \
    vendor/samsung/j1mini3g/proprietary/lib/lib_SoundAlive_play_plus_ver126a.so:system/lib/lib_SoundAlive_play_plus_ver126a.so \
    vendor/samsung/j1mini3g/proprietary/lib/lib_soundaliveresampler.so:system/lib/lib_soundaliveresampler.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsoundalive.so:system/lib/libsoundalive.so \
    vendor/samsung/j1mini3g/proprietary/lib/lib_SoundAlive_SRC192_ver205.so:system/lib/lib_SoundAlive_SRC192_ver205.so \
    vendor/samsung/j1mini3g/proprietary/lib/lib_SoundAlive_ver118t.so:system/lib/lib_SoundAlive_ver118t.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsoundspeed.so:system/lib/libsoundspeed.so \
    vendor/samsung/j1mini3g/proprietary/lib/libspaf.so:system/lib/libspaf.so \
    vendor/samsung/j1mini3g/proprietary/lib/libspdkeygen.so:system/lib/libspdkeygen.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsprdftms.so:system/lib/libsprdftms.so \
    vendor/samsung/j1mini3g/proprietary/lib/libsprdlsc.so:system/lib/libsprdlsc.so \
    vendor/samsung/j1mini3g/proprietary/lib/libvariablespeed.so:system/lib/libvariablespeed.so \
    vendor/samsung/j1mini3g/proprietary/lib/libvtmanager.so:system/lib/libvtmanager.so \
    vendor/samsung/j1mini3g/proprietary/lib/libvtstack.so:system/lib/libvtstack.so \
    vendor/samsung/j1mini3g/proprietary/lib/libynoise.so:system/lib/libynoise.so \
    vendor/samsung/j1mini3g/proprietary/lib/modules/pskey_bt.txt:system/lib/modules/pskey_bt.txt \
    vendor/samsung/j1mini3g/proprietary/lib/soundfx/libaudioeffectoffload.so:system/lib/soundfx/libaudioeffectoffload.so \
    vendor/samsung/j1mini3g/proprietary/lib/soundfx/libaudiosa_sec.so:system/lib/soundfx/libaudiosa_sec.so \
    vendor/samsung/j1mini3g/proprietary/lib/soundfx/libmyspace.so:system/lib/soundfx/libmyspace.so \
    vendor/samsung/j1mini3g/proprietary/vendor/etc/audio_effects.conf:system/vendor/etc/audio_effects.conf \
    vendor/samsung/j1mini3g/proprietary/vendor/firmware/vbc_eq:system/vendor/firmware/vbc_eq \
    vendor/samsung/j1mini3g/proprietary/vendor/lib/libwvdrm_L3.so:system/vendor/lib/libwvdrm_L3.so \
    vendor/samsung/j1mini3g/proprietary/vendor/lib/mediadrm:system/vendor/lib/mediadrm \
    vendor/samsung/j1mini3g/proprietary/vendor/lib/mediadrm/libdrmclearkeyplugin.so:system/vendor/lib/mediadrm/libdrmclearkeyplugin.so \
    vendor/samsung/j1mini3g/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:system/vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/j1mini3g/proprietary/vendor/media/LMspeed_508.emd:system/vendor/media/LMspeed_508.emd \
    vendor/samsung/j1mini3g/proprietary/vendor/media/PFFprec_600.emd:system/vendor/media/PFFprec_600.emd
